[package]
name = "webf"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11", features = ["json", "gzip"] }
futures = "0.3"
md5 = "0.7.0"
rand = "0.8.5"
